swagger: '2.0'
schemes:
  - http
  - https
host: localhost:8080
basePath: /
info:
  $ref: ./info/index.yaml
tags:
  $ref: ./tags/index.yaml
securityDefinitions:
  api_key:
    type: apiKey
    name: autoCookie
    in: header
paths:
 $ref: ./paths/index.yaml
definitions:
 $ref: ./definitions/index.yaml
